# Generated by Django 5.0.4 on 2024-07-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_curso_delete_foro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='theme',
            new_name='grado',
        ),
    ]
