# Generated by Django 5.0.4 on 2024-07-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_rename_theme_curso_grado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='name',
            new_name='nombre',
        ),
    ]
