# Generated by Django 4.2.5 on 2024-07-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_cursos_paralelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Asignatura',
        ),
    ]
