# Generated by Django 4.2.5 on 2024-07-10 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_asignaturas_curso_delete_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(db_column='correo', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
