# Generated by Django 5.0.4 on 2024-07-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_foro_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foro',
            old_name='topic',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='user',
            new_name='usuario',
        ),
    ]
