# Generated by Django 5.0.4 on 2024-07-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_rename_topic_foro_tema_rename_user_foro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='discuss',
            new_name='discusion',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='foro',
            new_name='hilo',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='date_created',
            new_name='fecha_creacion',
        ),
    ]
