# Generated by Django 4.2.6 on 2024-07-10 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='comunicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='entregable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Nuevo_Post', max_length=150),
        ),
        migrations.CreateModel(
            name='repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nuevo_Repo', max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.asignaturas')),
                ('posts', models.ManyToManyField(related_name='posts', to='Core.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='repositorios',
            field=models.ManyToManyField(related_name='repositorios', to='Core.repositorio'),
        ),
        migrations.AddField(
            model_name='post',
            name='repositorio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Core.repositorio'),
        ),
    ]
