# Generated by Django 4.2.6 on 2024-07-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_remove_post_content_remove_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorio',
            name='usuario',
        ),
    ]
