# Generated by Django 4.2.6 on 2024-05-27 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='fechaNacimiento')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('tipo', models.CharField(choices=[('Stu', 'Estudiante'), ('Tea', 'Profesor'), ('Str', 'Otro')], max_length=3, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True)),
                ('super', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
